### ISSUE TITLE
CTD unjam mark

### ISSUE THREAD

**Issue by morobukan** [Aoldri/anomaly-addon-deps#3]
hello, Author. I just update to 2.7.0 and have this error popup

FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_pcall_failed
[error]File          : D:\a\xray-monolith\xray-monolith\src\xrServerEntities\script_engine.cpp
[error]Line          : 262
[error]Description   : fatal error
[error]Arguments     : 
 1 : [Lua] c:/efp\gamedata\scripts\unjam_motion_mark.script(15) : func_or_userdata
 
LUA error: c:/efp\gamedata\scripts\unjam_motion_mark.script:15: attempt to call method 'SetMisfire' (a nil value)

can u help? thanks in advance

**Comment by Aoldri** [comment]
Somehow I missed this, but it should be fixed now
